service:
  type: LoadBalancer

persistence:
  enabled: true

adminUser: admin
adminPassword: admin123

plugins:
   - grafana-kubernetes-app

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://telemetry-prometheus-server.telemetry.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Elastic
      type: elasticsearch
      access: proxy
      database: "[logstash-]YYYY.MM.DD"
      url: http://elasticsearch-master:9200
      jsonData:
        interval: Daily
        timeField: "@timestamp"
        esVersion: 70

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'Auto-configured-dashboards'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    k8s-cluster-summary:
      file: dashboards/k8s-cluster-summary_rev1.json
    docker-host-container-overview:
      file: dashboards/docker-host-container-overview.json
    kubernetes-cluster-monitoring:
      file: dashboards/kubernetes-cluster-monitoring-via-prometheus_rev1.json
    elasticsearch:
      file: dashboards/elasticsearch_rev1.json
